import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import db from './db.js';
import { z } from 'zod';

const app=express(); app.use(cors()); app.use(express.json());
const money=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
const customerSchema=z.object({name:z.string().trim().min(1),mobile:z.string().trim().min(7).max(20),email:z.string().email().optional().or(z.literal('')),address:z.string().optional().default('')});
const productSchema=z.object({name:z.string().trim().min(1),category:z.string().optional().default(''),unit:z.string().min(1),price:z.number().nonnegative(),tax:z.number().nonnegative(),stock:z.number().nonnegative(),description:z.string().optional().default('')});
const billSchema=z.object({customerId:z.number().int().positive().nullable().optional(),items:z.array(z.object({productId:z.number().int().positive(),quantity:z.number().positive(),discount:z.number().nonnegative()})).min(1),paymentMethod:z.enum(['Cash','UPI','Card','Other']),paymentStatus:z.enum(['Paid','Pending','Partially Paid']),paidAmount:z.number().nonnegative().default(0)});
function nextInvoice(prefix:string){const row=db.prepare('SELECT invoice_number FROM bills ORDER BY id DESC LIMIT 1').get() as any; const n=row?Number(String(row.invoice_number).replace(/\D/g,''))||0:0; return `${prefix}${String(n+1).padStart(5,'0')}`}
function error(res:any,e:any){const msg=e?.issues?.map((x:any)=>x.message).join(', ')||e?.message||'Request failed'; return res.status(400).json({error:msg});}
app.get('/api/health',(_,res)=>res.json({ok:true}));
app.get('/api/customers',(req,res)=>{const q=String(req.query.q||'').trim(); const rows=db.prepare('SELECT * FROM customers WHERE name LIKE ? OR mobile LIKE ? OR email LIKE ? ORDER BY id DESC').all(`%${q}%`,`%${q}%`,`%${q}%`); res.json(rows)});
app.post('/api/customers',(req,res)=>{try{const x=customerSchema.parse(req.body); const r=db.prepare('INSERT INTO customers(name,mobile,email,address) VALUES (?,?,?,?)').run(x.name,x.mobile,x.email||null,x.address||''); res.status(201).json(db.prepare('SELECT * FROM customers WHERE id=?').get(r.lastInsertRowid))}catch(e){error(res,e)}});
app.put('/api/customers/:id',(req,res)=>{try{const x=customerSchema.parse(req.body); db.prepare('UPDATE customers SET name=?,mobile=?,email=?,address=? WHERE id=?').run(x.name,x.mobile,x.email||null,x.address||'',req.params.id); res.json(db.prepare('SELECT * FROM customers WHERE id=?').get(req.params.id))}catch(e){error(res,e)}});
app.delete('/api/customers/:id',(req,res)=>{try{db.prepare('DELETE FROM customers WHERE id=?').run(req.params.id); res.status(204).end()}catch(e){error(res,e)}});
app.get('/api/products',(req,res)=>{const q=String(req.query.q||'').trim(); const rows=db.prepare('SELECT * FROM products WHERE name LIKE ? OR category LIKE ? ORDER BY id DESC').all(`%${q}%`,`%${q}%`); res.json(rows)});
app.post('/api/products',(req,res)=>{try{const x=productSchema.parse(req.body); const r=db.prepare('INSERT INTO products(name,category,unit,price,tax,stock,description) VALUES (?,?,?,?,?,?,?)').run(x.name,x.category,x.unit,x.price,x.tax,x.stock,x.description); res.status(201).json(db.prepare('SELECT * FROM products WHERE id=?').get(r.lastInsertRowid))}catch(e){error(res,e)}});
app.put('/api/products/:id',(req,res)=>{try{const x=productSchema.parse(req.body); db.prepare('UPDATE products SET name=?,category=?,unit=?,price=?,tax=?,stock=?,description=? WHERE id=?').run(x.name,x.category,x.unit,x.price,x.tax,x.stock,x.description,req.params.id); res.json(db.prepare('SELECT * FROM products WHERE id=?').get(req.params.id))}catch(e){error(res,e)}});
app.delete('/api/products/:id',(req,res)=>{try{db.prepare('DELETE FROM products WHERE id=?').run(req.params.id); res.status(204).end()}catch(e){error(res,e)}});
app.get('/api/bills',(req,res)=>{const q=String(req.query.q||'').trim(); const status=String(req.query.status||''); const rows=db.prepare(`SELECT b.*, c.name customer_name FROM bills b LEFT JOIN customers c ON c.id=b.customer_id WHERE (b.invoice_number LIKE ? OR COALESCE(c.name,'') LIKE ?) ${status? 'AND b.payment_status=?':''} ORDER BY b.id DESC`).all(`%${q}%`,`%${q}%`,...(status?[status]:[])); res.json(rows)});
app.get('/api/bills/:id',(req,res)=>{const bill=db.prepare('SELECT b.*, c.name customer_name,c.mobile customer_mobile,c.email customer_email,c.address customer_address FROM bills b LEFT JOIN customers c ON c.id=b.customer_id WHERE b.id=?').get(req.params.id) as any; if(!bill) return res.status(404).json({error:'Invoice not found'}); bill.items=db.prepare('SELECT * FROM bill_items WHERE bill_id=? ORDER BY id').all(req.params.id); bill.payments=db.prepare('SELECT * FROM payments WHERE bill_id=? ORDER BY id').all(req.params.id); res.json(bill)});
const createBill=db.transaction((payload:any)=>{const settings=db.prepare('SELECT * FROM business_settings WHERE id=1').get() as any; const products=db.prepare('SELECT * FROM products WHERE id IN ('+payload.items.map(()=>'?').join(',')+')').all(...payload.items.map((i:any)=>i.productId)) as any[]; if(products.length!==payload.items.length) throw new Error('One or more products are invalid'); const prepared=payload.items.map((i:any)=>{const p=products.find((x:any)=>x.id===i.productId)!; if(p.stock<i.quantity) throw new Error(`Insufficient stock for ${p.name}`); const base=i.quantity*p.price; const afterDiscount=Math.max(0,base-i.discount); const tax=afterDiscount*(p.tax/100); return {...i,p,base,afterDiscount,tax,amount:afterDiscount+tax};}); const subtotal=money(prepared.reduce((s:any,x:any)=>s+x.base,0)); const discount=money(prepared.reduce((s:any,x:any)=>s+x.discount,0)); const tax=money(prepared.reduce((s:any,x:any)=>s+x.tax,0)); const grand=money(prepared.reduce((s:any,x:any)=>s+x.amount,0)); const invoice=nextInvoice(settings.invoice_prefix); const bill=db.prepare('INSERT INTO bills(invoice_number,customer_id,date,subtotal,discount,tax,grand_total,payment_method,payment_status) VALUES (?,?,?,?,?,?,?,?,?)').run(invoice,payload.customerId??null,new Date().toISOString(),subtotal,discount,tax,grand,payload.paymentMethod,payload.paymentStatus); for(const x of prepared){db.prepare('INSERT INTO bill_items(bill_id,product_id,product_name,quantity,rate,discount,tax,amount) VALUES (?,?,?,?,?,?,?,?)').run(bill.lastInsertRowid,x.p.id,x.p.name,x.quantity,x.p.price,x.discount,x.tax,x.amount); db.prepare('UPDATE products SET stock=stock-? WHERE id=?').run(x.quantity,x.p.id)} if(payload.paidAmount>0) db.prepare('INSERT INTO payments(bill_id,amount,method,status) VALUES (?,?,?,?)').run(bill.lastInsertRowid,payload.paidAmount,payload.paymentMethod,payload.paymentStatus); return db.prepare('SELECT * FROM bills WHERE id=?').get(bill.lastInsertRowid)});
app.post('/api/bills',(req,res)=>{try{const p=billSchema.parse(req.body); res.status(201).json(createBill(p))}catch(e){error(res,e)}});
app.delete('/api/bills/:id',(req,res)=>{try{const b=db.prepare('SELECT * FROM bill_items WHERE bill_id=?').all(req.params.id) as any[]; const remove=db.transaction(()=>{for(const x of b) db.prepare('UPDATE products SET stock=stock+? WHERE id=?').run(x.quantity,x.product_id); db.prepare('DELETE FROM bills WHERE id=?').run(req.params.id)}); remove(); res.status(204).end()}catch(e){error(res,e)}});
app.get('/api/settings',(_,res)=>res.json(db.prepare('SELECT * FROM business_settings WHERE id=1').get()));
app.put('/api/settings',(req,res)=>{const allowed=['business_name','address','phone','email','gst_number','invoice_prefix','currency','default_tax','invoice_footer']; const s=req.body||{}; try{db.prepare(`UPDATE business_settings SET ${allowed.map(k=>k+'=?').join(',')} WHERE id=1`).run(...allowed.map(k=>s[k])); res.json(db.prepare('SELECT * FROM business_settings WHERE id=1').get())}catch(e){error(res,e)}});
app.get('/api/dashboard',(_,res)=>{const sales=(db.prepare("SELECT COALESCE(SUM(grand_total),0) v FROM bills WHERE date(date)=date('now','localtime')").get() as any).v; const total=(db.prepare('SELECT COALESCE(SUM(grand_total),0) v FROM bills').get() as any).v; const pending=(db.prepare("SELECT COALESCE(SUM(grand_total),0) v FROM bills WHERE payment_status!='Paid'").get() as any).v; res.json({todaySales:money(sales),totalSales:money(total),totalBills:(db.prepare('SELECT COUNT(*) c FROM bills').get() as any).c,totalCustomers:(db.prepare('SELECT COUNT(*) c FROM customers').get() as any).c,totalProducts:(db.prepare('SELECT COUNT(*) c FROM products').get() as any).c,pendingPayments:money(pending),recentBills:db.prepare('SELECT b.id,b.invoice_number,b.grand_total,b.payment_status,c.name customer_name FROM bills b LEFT JOIN customers c ON c.id=b.customer_id ORDER BY b.id DESC LIMIT 6').all()})});

app.listen(Number(process.env.PORT||4000),()=>console.log('AB Billing API running'));
export default app;
